name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Options
          user: veera-crt
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Calcutta
          
          # Theme (Tokyonight to match your brand)
          config_theme: community/tokyonight
          
          # The "Spider/Radar" Chart you wanted (Followup Plugin)
          plugin_followup: yes
          plugin_followup_sections: repositories
          
          # Extra Stats
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most
          
